sudo: required
services:
    - docker
before_install:
    - docker build -t currency-exchange-service:latest -f Dockerfile.dev .
#script:
#    - docker run -p 18081:8001 -t -i currency-exchange-service