# fetch basic image
FROM maven:3.3.9-jdk-8

# application placed into /opt/app
RUN mkdir -p /opt/app
WORKDIR /opt/app

RUN mvn install

COPY ./ .

RUN mvn package

# local application port
EXPOSE 8080

# execute it
CMD ["java","-jar","/opt/app/target/currency-exchange-service-0.0.1.jar"]